spring.application.name=springboot-application

# 環境変数があればそれを使い、無ければローカル用(db:5432)を使う
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver