spring.application.name=springboot-application

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.flyway.validate-on-migrate=false
spring.flyway.enabled=false
server.port=${PORT:8080}


# MyBatisのアンダースコア（スネークケース）をキャメルケースに自動変換する設定
mybatis.configuration.map-underscore-to-camel-case=true

# ファイルサイズの合計の最大値
spring.servlet.multipart.max-file-size=1MB

# リクエストサイズの最大値
spring.servlet.multipart.max-request-size=10MB
